export default [
  {
    Column: 1,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 2,
    Number: "1",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  /*{
    Column: 2,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "2",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },*/
  {
    Column: 3,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "True",
    Length: 1,
    Number: "3",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 4,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "4",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 5,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "5",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 6,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "6",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 7,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "7",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 8,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "8",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 9,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "9",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 10,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "10",
    Row: 1,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 1,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "11",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 2,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "12",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 3,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "13",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 4,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "14",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 5,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "15",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 6,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "16",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 7,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "17",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 8,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "18",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 9,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "19",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 10,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "20",
    Row: 2,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 10,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "41",
    Row: 3,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 1,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "21",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 2,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "22",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 3,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "23",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 4,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "24",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 5,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "25",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 6,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "26",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 7,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "27",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 8,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "28",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 9,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "29",
    Row: 4,
    Width: 2,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 10,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "30",
    Row: 4,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 1,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "31",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 2,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "32",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 3,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "33",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 4,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "34",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 5,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "35",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 6,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "36",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 7,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "37",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  {
    Column: 8,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "38",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },
  /*{
    Column: 9,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "39",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  },*/
  {
    Column: 10,
    Fare: "500",
    NetFare: "500",
    IsAvailableSeat: "True",
    IsLadiesSeat: "False",
    Length: 1,
    Number: "40",
    Row: 5,
    Width: 1,
    Zindex: 0,
    etravosApitax: "75",
    OperatoretravosApiCharge: "10.00",
    SeatCode: null,
    BookingFee: 0,
    TollFee: 0,
    LevyFare: 0,
    SrtFee: 0
  }
];
