export const DOMESTIC_SUGGESTION = "DOMESTIC_SUGGESTION";
export const INTERNATIONAL_SUGGESTION = "INTERNATIONAL_SUGGESTION";
export const DOMESTIC_HOTEL_SUGGESTION = "DOMESTIC_HOTEL_SUGGESTION";
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const BUS_SUGGESTION = "BUS_SUGGESTION";
